
# You can change the default http port
server:
  port: 16722
  servlet:
    path: /njdp

# default db config

## Mybatis 配置typeAliasesPackage: com.njty.tydp.mapper

spring:
  datasource:
    url: jdbc:oracle:thin:@58.213.107.82:1521:orcl
    username: buspos
    password: njtynjty
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    


    #url: jdbc:mysql://127.0.0.1:3306/xyl?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #data-username: root
    #data-password: _Jf0<aY->Aos
    #driver-class-name: com.mysql.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource



