
# You can change the default http port
server:
  port: 16722
  servlet:
    path: /njdp

# default db config

## Mybatis 配置typeAliasesPackage: com.njty.tydp.mapper

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xyl?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    data-username: root
    data-password: _Jf0<aY->Aos
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.njty.tydp.mapper

